In [1]:
import numpy as np

属性名字	属性解释

ndarray.shape	数组维度的元组

ndarray.ndim	数组维数

ndarray.size	数组中的元素数量

ndarray.itemsize	一个数组元素的长度（字节）

ndarray.dtype	数组元素的类型

生成0和1的数组

np.ones(shape, dtype)

np.ones_like(a, dtype)

np.zeros(shape, dtype)

np.zeros_like(a, dtype)

In [2]:
ones = np.ones([4,8])
np.zeros_like(ones)

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

# np.linspace (start, stop, num, endpoint)
创建等差数组 — 指定数量
参数:
- start:序列的起始值
- stop:序列的终止值
- num:要生成的等间隔样例数量，默认为50
- endpoint:序列中是否包含stop值，默认为ture

In [3]:
np.linspace(0, 100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

# np.arange(start,stop, step, dtype)
- 创建等差数组 — 指定步长
- 参数
- step:步长,默认值为1

In [5]:
np.arange(10, 50, step = 2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

# np.logspace(start,stop, num)
- 创建等比数列

- 参数:

- num:要生成的等比数列数量，默认为50

In [8]:
# 生成10^x
np.logspace(0, 2, 3)

array([  1.,  10., 100.])

# 生成随机数np.random模块

- np.random.randn(d0, d1, …, dn)

功能：从标准正态分布中返回一个或多个样本值

- np.random.normal(loc=0.0, scale=1.0, size=None)

loc：float

​ 此概率分布的均值（对应着整个分布的中心centre）

scale：float

​ 此概率分布的标准差（对应于分布的宽度，scale越大越矮胖，scale越小，越瘦高）

size：int or tuple of ints

​ 输出的shape，默认为None，只输出一个值

- np.random.standard_normal(size=None)

返回指定形状的标准正态分布的数组。

In [11]:
#举例1：生成均值为1.75，标准差为1的正态分布数据，100000000个
x1 = np.random.normal(1.75, 1, 100000000)

In [12]:
#均值为 0,标准差为 1,shape=(4, 5)
stock_change = np.random.normal(0, 1, (4, 5))
stock_change

array([[ 0.28468594, -0.69792387,  1.46524869, -0.83211551, -2.05944153],
       [ 1.1685702 , -0.0967921 ,  0.41345497,  1.49858261, -0.34280272],
       [-2.55183303, -0.40988686,  0.2949274 , -0.16468308,  0.74333649],
       [ 0.26193938,  0.72992068, -0.01472978,  0.46516869, -0.5290431 ]])

# 均匀分布
- np.random.rand(d0, d1, ..., dn)
返回[0.0，1.0)内的一组均匀分布的数。


- np.random.uniform(low=0.0, high=1.0, size=None)
功能：从一个均匀分布[low,high)中随机采样，注意定义域是左闭右开，即包含low，不包含high.
参数介绍:
low: 采样下界，float类型，默认值为0；
high: 采样上界，float类型，默认值为1；
size: 输出样本数目，为int或元组(tuple)类型，例如，size=(m,n,k), 则输出mnk个样本，缺省时输出1个值。
返回值：ndarray类型，其形状和参数size中描述一致。


- np.random.randint(low, high=None, size=None, dtype='l')
从一个均匀分布中随机采样，生成一个整数或N维整数数组，
取数范围：若high不为None时，取[low,high)之间随机整数，否则取值[0,low)之间随机整数。

In [13]:
# 生成均匀分布的随机数
x2 = np.random.uniform(-1, 1, 100000000)

# 类型修改
ndarray.astype(type)

# 数组的去重
np.unique()

In [16]:
temp = np.array([[1, 2, 3, 4],[3, 4, 5, 6]])
np.unique(temp)

array([1, 2, 3, 4, 5, 6])

# np.all
所有元素都满足条件返回 true,否则 false

In [19]:
#判断前两名同学的成绩[0:2, :]是否全及格
score = np.random.randint(40, 100, (10, 5))
np.all(score[0:2, :] > 60)

False

# np.any
所有元素 有一个满足就返回 true,

In [20]:
# 判断前两名同学的成绩[0:2, :]是否有大于90分的
np.any(score[0:2, :] > 80)

True

# np.where（三元运算符）

In [21]:
# 判断前四名学生,前四门课程中，成绩中大于60的置为1，否则为0
temp = score[:4, :4]
np.where(temp > 60, 1, 0)

array([[0, 1, 1, 0],
       [0, 1, 1, 1],
       [1, 1, 1, 0],
       [1, 0, 1, 0]])

# np.logical_and和np.logical_or

In [22]:
# 判断前四名学生,前四门课程中，成绩中大于60且小于90的换为1，否则为0
np.where(np.logical_and(temp > 60, temp < 90), 1, 0)

# 判断前四名学生,前四门课程中，成绩中大于90或小于60的换为1，否则为0
np.where(np.logical_or(temp > 90, temp < 60), 1, 0)

array([[1, 0, 0, 1],
       [1, 0, 0, 0],
       [0, 0, 0, 1],
       [0, 1, 0, 1]])